version: '3.8'

services:
  postgres:
    container_name: loja_virtual
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lojadb